version: '3.8'

services:
  ibkr_db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=ibkr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    container_name: ibkr_db
    volumes:
      - ibkr_db:/var/lib/postgresql/data

  ibkr_web:
    build: ./app
    ports: 
      - '8000:8000'
    container_name: ibkr_web
    volumes:
      - /home/taiconley/Desktop/Projects/ibkr:/ibkr

  ibkr_jupyter:
    build: ./jupyter
    volumes:
      - /home/taiconley/Desktop/Projects/ibkr:/ibkr
    ports:
      - '8888:8888'
    container_name: ibkr_jupyter
    depends_on:
      - ibkr_db
    privileged: true
    runtime: nvidia
    restart: "no"

volumes:
  ibkr_db:
  ibkr_web:
  # jupyter: